/** Product guide copy. Other locales use the store's English fallback. */
export const tourEn = {
  'tour.guide': 'The tazdan guide',
  'tour.details': 'How it works',
  'tour.back': 'Previous chapter',
  'tour.next': 'Next chapter',
  'tour.done': 'Back to the app',
  'tour.replay': 'Explore the app',
  'tour.replayBody': 'Your guide to money, markets and more',
  'tour.intro.label': 'YOUR WORLD. CONNECTED.',
  'tour.intro.title': 'Your world.\nOne wallet.',
  'tour.intro.body': 'Everyday money meets digital assets. Hold, exchange and send from one beautifully simple home.',
  'tour.intro.detail1': 'A home for your money',
  'tour.intro.explain1': 'Home brings your balances, market prices and recent activity together. Use Buy, Sell, Send, Receive or Top up to make your next move.',
  'tour.intro.detail2': 'Find your way around',
  'tour.intro.explain2': 'Wallets organises your assets. Messages connects you with people. P2P shows the marketplace, and Profile holds your settings, verification and support.',
  'tour.wallets.label': '01 / YOUR MONEY',
  'tour.wallets.title': 'Many currencies.\nOne clear picture.',
  'tour.wallets.body': 'Keep dinars, dollars and supported crypto together. See each balance and explore an asset in a tap.',
  'tour.wallets.detail1': 'Balances, without the guesswork',
  'tour.wallets.explain1': 'Filter your wallet by crypto or fiat. Each asset keeps its own balance; the combined value is an estimate that changes with market prices and exchange rates.',
  'tour.wallets.detail2': 'Follow every movement',
  'tour.wallets.explain2': 'Open activity to find payments, exchanges, deposits and withdrawals. Check an individual transaction for its amount, fees and current status.',
  'tour.funding.label': '02 / ADD & RECEIVE',
  'tour.funding.title': 'Your next move\nstarts here.',
  'tour.funding.body': 'Receive from another member, use an available bank transfer method, or deposit supported crypto.',
  'tour.funding.detail1': 'Choose how money arrives',
  'tour.funding.explain1': 'Top up shows the methods available for your account and currency. Receive lets you share your handle or payment details. Bank deposits may need a reference and time to be reviewed.',
  'tour.funding.detail2': 'Match the coin and network',
  'tour.funding.explain2': 'For crypto, select the exact asset and network shown on the deposit screen before copying the address. A transfer on the wrong network can be lost. Network confirmations affect arrival times.',
  'tour.rate.label': '03 / EXCHANGE',
  'tour.rate.title': 'Your exchange.\nEvery detail.',
  'tour.rate.body': 'Buy, sell or exchange supported assets. Review the quote, fees and receiving amount before confirming.',
  'tour.rate.detail1': 'A quote you can review',
  'tour.rate.explain1': 'Choose the currencies and enter an amount. The quote shows your rate, fees and the amount to receive. If the quote expires, refresh it and review the new price before proceeding.',
  'tour.rate.detail2': 'Keep the market in perspective',
  'tour.rate.explain2': 'Charts and price changes help you follow markets; they do not predict returns. Crypto prices can move sharply. Only supported assets and available trading services can be exchanged.',
  'tour.send.label': '04 / MONEY & PEOPLE',
  'tour.send.title': 'Less distance.\nMore connection.',
  'tour.send.body': 'Send to a @handle, pay within a conversation, or share a claim link. Keep the payment and the conversation together.',
  'tour.send.detail1': 'Check, then send',
  'tour.send.explain1': 'Select the recipient and currency, enter an amount, then check the recipient, fees and total. Larger payments may require an additional confirmation code.',
  'tour.send.detail2': 'Links and withdrawals',
  'tour.send.explain2': 'A claim link lets someone collect a payment after signing in or registering. Keep the link private and check its status. External withdrawals have their own verification, network fees and processing times.',
  'tour.explore.label': '05 / YOUR EVERYDAY TOOLKIT',
  'tour.explore.title': 'More possibility.\nSame simple app.',
  'tour.explore.body': 'Organise money with budgets and pools, explore P2P offers, and manage cards where those services are available.',
  'tour.explore.detail1': 'Plan, share and track',
  'tour.explore.explain1': 'Budgets help organise your money; pools bring people together around a shared goal. Activity keeps the record. Business accounts also have invoice and bulk payment tools.',
  'tour.explore.detail2': 'Services that fit your account',
  'tour.explore.explain2': 'On P2P, review an offer’s price, limits and payment method and follow the trade instructions. Never mark a payment received before checking it. Cards and new P2P trades can be unavailable or paused; the app shows their current availability.',
  'tour.security.label': '06 / STAY IN CONTROL',
  'tour.security.title': 'Your money.\nYour peace of mind.',
  'tour.security.body': 'Verify your identity, enable two-factor sign-in and review your devices. Good security starts with you.',
  'tour.security.detail1': 'Make your account yours',
  'tour.security.explain1': 'Verification connects your account to your identity and determines available limits and services. In Settings, enable two-factor authentication and review trusted devices.',
  'tour.security.detail2': 'Keep access private',
  'tour.security.explain2': 'Never share your password or verification codes. Review payment details before approving them. If something looks unfamiliar, contact support from Profile.',
  'tour.start.label': 'READY WHEN YOU ARE',
  'tour.start.title': 'A new home\nfor your money.',
  'tour.start.body': 'Create an account, verify your identity and add your first funds. We’ll guide you through each step.',
  'tour.start.detail1': 'What you’ll need',
  'tour.start.explain1': 'Have your email address, phone number and a strong password ready. Identity verification may ask for identity documents and supporting information.',
  'tour.start.detail2': 'Set up at your own pace',
  'tour.start.explain2': 'Available services, limits and fees depend on your country, verification and account. You can revisit this guide from Profile whenever you need it.',
  'tour.available': 'Services depend on your country and verification.',
  'tour.funding.bank': 'Bank transfer',
  'tour.funding.crypto': 'Crypto deposit',
  'tour.funding.member': 'From a member',
  'tour.explore.budgets': 'Budgets & pools',
  'tour.explore.budgetsNote': 'Give your money a purpose',
  'tour.explore.p2p': 'Peer-to-peer',
  'tour.explore.p2pNote': 'Explore available offers',
  'tour.explore.cards': 'Cards',
  'tour.explore.cardsNote': 'Manage where available',
};

export const tourAr: Record<keyof typeof tourEn, string> = {
  'tour.guide': 'دليلك إلى تزدان',
  'tour.details': 'كيف يعمل التطبيق',
  'tour.back': 'القسم السابق',
  'tour.next': 'القسم التالي',
  'tour.done': 'العودة إلى التطبيق',
  'tour.replay': 'اكتشف التطبيق',
  'tour.replayBody': 'دليلك إلى الأموال والأسواق والمزيد',
  'tour.intro.label': 'عالمك. متصل.',
  'tour.intro.title': 'عالمك.\nمحفظة واحدة.',
  'tour.intro.body': 'أموالك اليومية وأصولك الرقمية في مكان واحد. احتفظ وحوّل وأرسل بكل بساطة.',
  'tour.intro.detail1': 'بيت جديد لأموالك',
  'tour.intro.explain1': 'تجمع الرئيسية أرصدتك وأسعار الأسواق وآخر الأنشطة. اختر شراء أو بيع أو إرسال أو استلام أو إيداع لخطوتك التالية.',
  'tour.intro.detail2': 'تعرّف على أقسام التطبيق',
  'tour.intro.explain2': 'المحافظ تنظّم أصولك، والرسائل تصلك بالآخرين، وسوق P2P يعرض العروض المتاحة. وفي الملف الشخصي تجد الإعدادات والتوثيق والدعم.',
  'tour.wallets.label': '01 / أموالك',
  'tour.wallets.title': 'عملات متعددة.\nصورة واضحة.',
  'tour.wallets.body': 'اجمع الدينار والدولار والعملات الرقمية المدعومة. اطّلع على كل رصيد واستكشف أي أصل بلمسة.',
  'tour.wallets.detail1': 'أرصدة واضحة',
  'tour.wallets.explain1': 'اعرض العملات الرقمية أو التقليدية في محفظتك. لكل أصل رصيده، والقيمة الإجمالية تقديرية وتتغيّر مع أسعار السوق والصرف.',
  'tour.wallets.detail2': 'تابع كل حركة',
  'tour.wallets.explain2': 'افتح النشاط للعثور على المدفوعات والتحويلات والإيداعات والسحوبات. افتح أي عملية للاطّلاع على مبلغها ورسومها وحالتها.',
  'tour.funding.label': '02 / الإيداع والاستلام',
  'tour.funding.title': 'خطوتك القادمة\nتبدأ هنا.',
  'tour.funding.body': 'استلم من مستخدم آخر، أو استخدم التحويل المصرفي المتاح، أو أودع عملات رقمية مدعومة.',
  'tour.funding.detail1': 'اختر طريقة وصول أموالك',
  'tour.funding.explain1': 'يعرض الإيداع الطرق المتاحة لحسابك وعملتك، ويتيح الاستلام مشاركة اسم المستخدم أو بيانات الدفع. قد يحتاج الإيداع المصرفي إلى رقم مرجعي ووقت للمراجعة.',
  'tour.funding.detail2': 'طابق العملة والشبكة',
  'tour.funding.explain2': 'اختر العملة والشبكة المحددتين في شاشة الإيداع قبل نسخ العنوان. قد يُفقد التحويل على شبكة خاطئة، ويتأثر وقت الوصول بتأكيدات الشبكة.',
  'tour.rate.label': '03 / الصرف والتداول',
  'tour.rate.title': 'افهم الأرقام.\nثم اختر خطوتك.',
  'tour.rate.body': 'اشترِ أو بِع أو حوّل الأصول المدعومة. راجع السعر والرسوم والمبلغ الذي ستستلمه قبل التأكيد.',
  'tour.rate.detail1': 'عرض سعر للمراجعة',
  'tour.rate.explain1': 'اختر العملات وأدخل المبلغ. يعرض التطبيق السعر والرسوم والمبلغ المستلم. إذا انتهت صلاحية العرض، حدّثه وراجع السعر الجديد قبل المتابعة.',
  'tour.rate.detail2': 'انظر إلى السوق بوعي',
  'tour.rate.explain2': 'تساعدك الرسوم البيانية وتغيّرات الأسعار على متابعة السوق ولا تتنبأ بالعوائد. قد تتحرك أسعار العملات الرقمية بسرعة. يتاح التداول للأصول والخدمات المدعومة فقط.',
  'tour.send.label': '04 / الأموال والناس',
  'tour.send.title': 'مسافات أقل.\nتواصل أكثر.',
  'tour.send.body': 'أرسل إلى @اسم مستخدم، أو ادفع داخل المحادثة، أو شارك رابط استلام. اجمع الدفع والحديث في مكان واحد.',
  'tour.send.detail1': 'راجع ثم أرسل',
  'tour.send.explain1': 'اختر المستلم والعملة وأدخل المبلغ، ثم راجع بيانات المستلم والرسوم والإجمالي. قد تحتاج المدفوعات الكبيرة إلى رمز تأكيد إضافي.',
  'tour.send.detail2': 'روابط الاستلام والسحب',
  'tour.send.explain2': 'يتيح رابط الاستلام تحصيل الدفعة بعد تسجيل الدخول أو إنشاء حساب. حافظ على خصوصية الرابط وتابع حالته. للسحب الخارجي متطلبات توثيق ورسوم شبكة وأوقات معالجة خاصة.',
  'tour.explore.label': '05 / أدواتك اليومية',
  'tour.explore.title': 'إمكانيات أكثر.\nبنفس البساطة.',
  'tour.explore.body': 'نظّم أموالك بالميزانيات والصناديق، واستكشف عروض P2P، وأدر بطاقاتك حيث تتوفر الخدمة.',
  'tour.explore.detail1': 'خطّط وشارك وتابع',
  'tour.explore.explain1': 'تساعدك الميزانيات على تنظيم أموالك، وتجمع الصناديق المشاركين حول هدف مشترك. يحفظ النشاط سجل العمليات. وتتضمن حسابات الأعمال أدوات الفواتير والدفعات الجماعية.',
  'tour.explore.detail2': 'خدمات تناسب حسابك',
  'tour.explore.explain2': 'راجع سعر عرض P2P وحدوده وطريقة الدفع واتبع تعليمات الصفقة. لا تؤكد استلام المال قبل التحقق منه. قد تكون البطاقات وصفقات P2P الجديدة غير متاحة أو متوقفة مؤقتاً؛ يوضح التطبيق حالتها.',
  'tour.security.label': '06 / تحكّم بحسابك',
  'tour.security.title': 'أموالك.\nوراحة بالك.',
  'tour.security.body': 'وثّق هويتك وفعّل المصادقة الثنائية وراجع أجهزتك. أمان حسابك يبدأ منك.',
  'tour.security.detail1': 'اجعل حسابك خاصاً بك',
  'tour.security.explain1': 'يربط التوثيق حسابك بهويتك ويحدد الحدود والخدمات المتاحة. فعّل المصادقة الثنائية وراجع الأجهزة الموثوقة من الإعدادات.',
  'tour.security.detail2': 'حافظ على خصوصية الدخول',
  'tour.security.explain2': 'لا تشارك كلمة المرور أو رموز التحقق. راجع تفاصيل الدفع قبل الموافقة. إذا لاحظت شيئاً غير مألوف، تواصل مع الدعم من الملف الشخصي.',
  'tour.start.label': 'عندما تكون مستعداً',
  'tour.start.title': 'بيت جديد\nلأموالك.',
  'tour.start.body': 'أنشئ حسابك ووثّق هويتك وأضف أول إيداع. سنرشدك في كل خطوة.',
  'tour.start.detail1': 'ما الذي تحتاجه',
  'tour.start.explain1': 'جهّز بريدك الإلكتروني ورقم هاتفك وكلمة مرور قوية. قد يُطلب منك مستند هوية ومعلومات إضافية أثناء التوثيق.',
  'tour.start.detail2': 'ابدأ على راحتك',
  'tour.start.explain2': 'تعتمد الخدمات والحدود والرسوم على بلدك وتوثيقك وحسابك. يمكنك العودة لهذا الدليل من الملف الشخصي في أي وقت.',
  'tour.available': 'تعتمد الخدمات على بلدك ومستوى التوثيق.',
  'tour.funding.bank': 'تحويل مصرفي',
  'tour.funding.crypto': 'إيداع عملات رقمية',
  'tour.funding.member': 'من مستخدم آخر',
  'tour.explore.budgets': 'ميزانيات وصناديق',
  'tour.explore.budgetsNote': 'امنح أموالك هدفاً',
  'tour.explore.p2p': 'تداول بين الأفراد',
  'tour.explore.p2pNote': 'استكشف العروض المتاحة',
  'tour.explore.cards': 'البطاقات',
  'tour.explore.cardsNote': 'إدارة حيث تتوفر الخدمة',
};
