from pathlib import Path
import json
entries={
'chat.profile':'الملف الشخصي','chat.onlineNow':'متصل الآن','chat.lastSeen':'آخر ظهور {time}','chat.lastSeenUnavailable':'آخر ظهور غير متاح','chat.presenceHidden':'حالة الاتصال مخفية','chat.staffStatus':'فريق دعم تزدان','chat.profileBio':'نبذة','chat.handle':'المعرّف','chat.noHandle':'لم يُحدّد معرّف','chat.publicProfile':'الملف العام','chat.publicProfileOn':'ظاهر','chat.publicProfileOff':'خاص','chat.signupDate':'تاريخ الانضمام','chat.readReceiptsDescMutual':'عند إيقافها لن تتمكن من رؤية إيصالات قراءة الآخرين أيضاً.','chat.lastSeenTitle':'آخر ظهور وحالة الاتصال','chat.lastSeenDesc':'خصوصية متبادلة: تُخفى عن الطرفين إذا عطّلها أيّ منهما.','chat.requestMoney':'طلب مبلغ','chat.sendPayment':'إرسال دفعة','chat.stickers':'ملصقات','chat.messagePlaceholder':'رسالة','chat.replyAsSupport':'الرد باسم @support (مسؤول)','chat.replyingAsSupport':'الرد باسم @support','chat.requestFailed':'تعذّر الطلب','chat.requestFailedBody':'تعذّر إنشاء الطلب.','chat.paymentFailed':'تعذّر الدفع','chat.paymentFailedBody':'تعذّر إرسال الدفعة.','chat.replyFailed':'تعذّر الرد','chat.actionsTitle':'خيارات المحادثة','chat.viewProfile':'عرض الملف الشخصي','chat.blockUser':'حظر المستخدم','chat.reportUser':'الإبلاغ عن المستخدم','chat.escalateSupport':'التصعيد إلى الدعم','chat.blockTitle':'حظر {name}؟','chat.blockBody':'لن يتمكن أيّ منكما من مراسلة الآخر.','chat.block':'حظر','chat.blockFailed':'تعذّر الحظر','chat.escalateTitle':'التصعيد إلى الدعم؟','chat.escalateBody':'سينضم موظف من تزدان إلى المحادثة لمراجعة الصفقة. سيُبلّغ الطرفان بذلك.','chat.escalate':'تصعيد','chat.escalationOpened':'تم فتح طلب التصعيد','chat.escalationOpenedBody':'سيرد فريق الدعم عند مراجعة الطلب.','chat.escalateFailed':'تعذّر التصعيد','chat.reportMessage':'الإبلاغ عن رسالة','chat.message':'رسالة','chat.edit':'تعديل','chat.deleteTitle':'حذف هذه الرسالة؟','chat.deleteBody':'سيظهر مكانها «تم حذف الرسالة» لدى الطرفين.','chat.reportSubmitted':'تم إرسال البلاغ','chat.reportSubmittedBody':'شكراً لإبلاغنا، سيراجع فريقنا البلاغ.','chat.reportFailed':'تعذّر إرسال البلاغ','chat.reportTitle':'إبلاغ','chat.reportBody':'يراجع فريق الثقة والأمان في تزدان البلاغات. قد تؤثر البلاغات الكاذبة على حسابك.','chat.reportDetailsPlaceholder':'تفاصيل إضافية (اختياري)','chat.submitReport':'إرسال البلاغ',
'report.SPAM':'رسائل مزعجة أو غير مرغوبة','report.HARASSMENT':'مضايقة أو تنمّر','report.SCAM_FRAUD':'احتيال','report.IMPERSONATION':'انتحال شخصية','report.INAPPROPRIATE':'محتوى غير لائق','report.OTHER':'أخرى',
'chat.youSent':'أرسلت','chat.youReceived':'استلمت','chat.youRequested':'طلبت','chat.requestedFromYou':'طُلب منك','chat.deleted':'تم حذف الرسالة','chat.edited':'معدّلة','chat.loadingThread':'جارٍ التحميل…','chat.emptyThread':'رحّب بـ {name} — محادثتكما تبدأ الآن.','chat.sticker.paid':'تم الدفع','chat.sticker.moon':'أرسلها','chat.sticker.locked':'مؤمّن','chat.sticker.thanks':'شكراً','chat.sticker.deal':'اتفقنا','chat.sticker.chart':'إلى الأعلى','chat.sticker.verified':'تم','chat.sticker.gift':'لك',
'money.sendTitle':'إرسال دفعة','money.requestTitle':'طلب مبلغ','money.to':'إلى','money.from':'من','money.noWalletsTitle':'لا توجد محافظ','money.noWalletsBody':'موّل محفظة أولاً لإرسال دفعة في المحادثة.','money.amount':'المبلغ','money.max':'الحد الأقصى','money.exceedsBalance':'يتجاوز الرصيد المتاح','money.notePlaceholder':'ما سبب الدفعة؟ (اختياري)','money.requestNotePlaceholder':'أضف سبباً (اختياري)','money.sendCta':'إرسال {amount} {currency}','money.requestCta':'طلب {amount} {currency}','money.sendFallback':'إرسال الدفعة','money.requestFallback':'طلب مبلغ','money.availableSuffix':'متاح',
'receipt.pending':'قيد الانتظار','receipt.completed':'مكتمل','receipt.failed':'لم يكتمل',
'statements.title':'كشوف الحساب','statements.subtitle':'تصدير الأرصدة والرسوم وسجل العمليات للمراجعة','statements.center':'مركز كشوف الحساب','statements.rowsReady':'{count} عملية جاهزة','statements.preparing':'جارٍ إعداد المعاينة…','statements.choosePeriod':'اختر فترة للمعاينة','statements.transactions':'العمليات','statements.fees':'الرسوم','statements.deposits':'الإيداعات','statements.withdrawals':'السحوبات','statements.period':'الفترة','statements.month':'الشهر','statements.currency':'العملة','statements.thisMonth':'هذا الشهر','statements.lastMonth':'الشهر الماضي','statements.ytd':'من بداية السنة','statements.lastYear':'السنة الماضية','statements.allTime':'كل الفترات','statements.pickMonth':'اختر شهراً','statements.allCurrencies':'كل العملات','statements.pdf':'PDF · ورق A4 عمودي','statements.pdfDesc':'ملخص الحساب · الأرصدة · سجل العمليات الكامل','statements.recentRows':'آخر عمليات السجل','statements.noRows':'لا توجد عمليات تطابق خيارات الكشف.','statements.generating':'جارٍ الإنشاء…','statements.generate':'إنشاء كشف PDF','statements.failed':'تعذّر إنشاء الكشف','statements.tryAgain':'يرجى المحاولة مجدداً.','statements.noReference':'لا يوجد مرجع',
}
p=Path('mobile/src/store/i18nStore.ts');s=p.read_text();a=s.index('  ar: {',s.index('const dict:'));a+=len('  ar: {');s=s[:a]+'\n'+''.join('    '+json.dumps(k)+': '+json.dumps(v,ensure_ascii=False)+',\n' for k,v in entries.items())+s[a:];p.write_text(s)
