import json
from pathlib import Path
copy={
 'tz_hero_title_1':('Libya.','ليبيا.'),'tz_hero_title_2':('Crypto.','كريبتو.'),'tz_hero_title_3':('Connected.','متصلين.'),
 'tz_manifesto_1':('Your roots are Libyan. Your money has places to go.','جذورك ليبية. وفلوسك عندها وين تمشي.'),
 'tz_manifesto_2a':('Dinars. Crypto.','دينار. كريبتو.'),'tz_manifesto_2b':('Closer to your world.','أقرب لعالمك.'),
 'hero_line1':('Libyan roots.','جذور ليبية.'),'hero_line2':('Global money.','وفلوس عالمية.'),
 'hero_sub':('From dinars in Tripoli to family abroad. We’re bringing local money, crypto and international remittances into one familiar app, through approved partners.','من دينارك في طرابلس لأهلك برا البلاد. نجمعوا الفلوس المحلية والكريبتو والتحويلات الدولية في تطبيق قريب منك، عبر شركاء معتمدين.'),
 'bento_title_1':('Your dinar. Your crypto.','دينارك. وكريبتوك.'),'bento_title_2':('One *connected* wallet.','محفظة واحدة *متصلة*.'),
 'sec_social_title_1':('Across the city.','داخل مدينتك.'),'sec_social_title_2':('Across borders.','وعبر الحدود.'),
 'sec_social_desc':('A shared bill in Benghazi. Support for family overseas. Send and request money in the conversations you already have, with the total cost clear in LYD. Local and international routes are subject to launch approvals.','حساب مشترك في بنغازي. ودعم لأهلك برا. حوّل واطلب فلوس في محادثاتك اليومية، والتكلفة كاملة واضحة بالدينار. المسارات المحلية والدولية تخضع لموافقات الإطلاق.'),
 'feat_buy_eyebrow':('DINAR MEETS CRYPTO','الدينار يقابل الكريبتو'),'feat_buy_title':('A simpler way into crypto','بداية أسهل مع الكريبتو'),
 'feat_buy_desc':('Start with the amount you know in LYD. Explore supported crypto and see the conversion, fees and total before you confirm. Access will depend on local rules and approved providers.','ابدأ بمبلغ تعرفه بالدينار. استكشف الكريبتو المدعوم وشوف التحويل والرسوم والمبلغ الكامل قبل التأكيد. التوفر يعتمد على القواعد المحلية ومقدمي الخدمة المعتمدين.'),
 'feat_buy_f1':('LYD cost preview','التكلفة بالدينار'),'feat_buy_f3':('Partner-supported funding','تمويل عبر الشركاء'),'feat_buy_f4':('Supported assets','أصول مدعومة'),
 'feat_search_eyebrow':('YOUR CRYPTO, IN VIEW','كريبتوك، قدامك'),'feat_search_title':('Explore. Understand. Decide.','استكشف. افهم. قرّر.'),
 'feat_search_desc':('Follow supported assets, understand price moves and keep a clear view of your holdings. Your crypto and local money belong in the same conversation. Product preview; asset availability will vary.','تابع الأصول المدعومة وافهم حركة الأسعار وشوف أرصدتك بوضوح. كريبتوك وفلوسك المحلية في نفس الصورة. عرض للمنتج؛ توفر الأصول يختلف حسب الأهلية.'),
 'feat_search_f1':('Find supported assets','ابحث عن الأصول المدعومة'),'feat_search_f2':('Market insights','متابعة السوق'),'feat_search_f3':('Clear portfolio view','صورة واضحة للمحفظة'),'feat_search_f4':('LYD value context','قيمة واضحة بالدينار'),
 'feat_pay_title':('Local money. Global reach.','فلوس محلية. وصول عالمي.'),
 'feat_pay_desc':('Pay locally in dinars. Plan an international transfer with the exchange rate, fees and recipient amount in view. Crypto-supported routes are a planned option where legally permitted.','ادفع محلياً بالدينار. خطط لتحويل دولي وسعر الصرف والرسوم ومبلغ المستلم واضحين. المسارات المدعومة بالكريبتو خيار ضمن الخطة حيث يسمح القانون.'),
 'feat_pay_f2':('International remittances','تحويلات دولية'),'feat_pay_f3':('Supported crypto routes','مسارات كريبتو مدعومة'),
 'card_desc':('A card that brings your connected wallet into everyday spending. Our international card roadmap includes clear LYD costs and eligible funding options, subject to issuer and regulatory approval.','بطاقة تربط محفظتك المتصلة بمصاريفك اليومية. خطتنا للبطاقات الدولية تشمل تكاليف واضحة بالدينار وخيارات تمويل مؤهلة، بعد موافقة المُصدر والجهات التنظيمية.'),
 'onramp_headline':('From your dinar to your *world*.','من دينارك إلى *عالمك*.'),
 'onramp_buy_title':('Buy crypto','اشترِ كريبتو'),'onramp_buy_desc':('Explore supported assets with the total cost displayed in LYD. Funding and conversion depend on approved partners and local eligibility.','استكشف الأصول المدعومة والتكلفة الكاملة بالدينار. التمويل والتحويل مرتبطان بالشركاء المعتمدين والأهلية المحلية.'),
 'onramp_sell_title':('Back to dinars','ارجع للدينار'),'onramp_sell_desc':('A clearer route between crypto and local money is part of our vision. See available payout methods, rates and costs before making a decision.','مسار أوضح بين الكريبتو والفلوس المحلية جزء من رؤيتنا. شوف طرق الاستلام والأسعار والتكاليف المتاحة قبل القرار.'),
 'onramp_send_title':('Send internationally','حوّل دولياً'),'onramp_send_desc':('Keep family closer with transparent remittances. Approved corridors, recipient checks and local payout partners will determine availability.','خلّي أهلك أقرب بتحويلات واضحة. المسارات المعتمدة والتحقق من المستلم وشركاء الاستلام المحليون يحددوا التوفر.'),
 'cards_desc':('Shop online. Travel. Keep your money connected. We’re exploring international cards with regulated issuers, including eligible crypto conversion through partners. Fees and subscription pricing stay clear in LYD.','تسوق أونلاين. سافر. وخلّي فلوسك متصلة. نستكشف بطاقات دولية مع مُصدرين مرخّصين، وتحويل كريبتو مؤهل عبر الشركاء. الرسوم والباقات واضحة بالدينار.'),
 'cl_title':('Closer to home. With a *link*.','أقرب للدار. عبر *رابط*.'),
 'cl_sub':('A message to family. A payment for a friend. Our vision is to make money move as naturally as a conversation, across local and approved international routes.','رسالة لأهلك. ودفعة لصاحبك. رؤيتنا إن الفلوس تمشي بسهولة المحادثة، محلياً وعبر المسارات الدولية المعتمدة.'),
 'tz_bento_title_a':('Dinars, crypto and','دينار وكريبتو،'),'tz_bento_title_b':('a world of connection.','وعالم من التواصل.'),
 'tz_bento_send_title':('Libya to the people who matter.','من ليبيا للناس اللي تهمك.'),
 'tz_bento_send_desc':('International remittances with clear fees, recipient amounts and delivery status. A partner-led roadmap, built around Libyan lives.','تحويلات دولية برسوم ومبالغ استلام وحالة توصيل واضحة. خطة عبر الشركاء، مصممة لحياتنا في ليبيا.'),
 'tz_bento_secure_desc':('Identity checks, secure access and transaction monitoring are core requirements for our local, crypto and remittance routes.','التحقق من الهوية والدخول الآمن ومراقبة المعاملات متطلبات أساسية لمساراتنا المحلية والكريبتو والتحويلات.'),
 'pb_word_crypto':('crypto','الكريبتو'),'pb_sub':('Your dinar at home. Crypto in your wallet. Family across the world. One connected vision for Libyan money.','دينارك في البلاد. كريبتو في محفظتك. وأهلك حول العالم. رؤية واحدة متصلة لفلوسك الليبية.'),
 'pb_f_buy':('Buy crypto','شراء كريبتو'),'pb_f_sell':('Convert to LYD','تحويل للدينار'),'pb_f_p2p':('International transfers','تحويلات دولية'),'pb_f_multichain':('Crypto wallet','محفظة كريبتو'),'pb_f_global':('Global remittances','حوالات عالمية'),
 'minimal_cta_title':('Libya. Crypto. A world closer.','ليبيا. كريبتو. وعالم أقرب.'),'minimal_cta_desc':('Join the waitlist for a connected way to manage dinars, explore crypto and send money internationally. Built for Libya. Launch subject to approvals.','سجّل في القائمة لطريقة متصلة لإدارة دينارك واستكشاف الكريبتو والتحويل دولياً. مصممة لليبيا. الإطلاق يخضع للموافقات.'),
 'footer_statement':('Libyan roots. Crypto possibilities. Global connections.','جذور ليبية. إمكانيات كريبتو. وتواصل عالمي.'),
 'footer_tagline':('tazdan connects the vision of a LYD wallet, supported crypto and international remittances in one app built for Libya. Services are in development.','تزدان تجمع رؤية محفظة دينار وكريبتو مدعوم وتحويلات دولية في تطبيق لليبيا. الخدمات قيد التطوير.'),
 'footer_disclaimer_loss':('tazdan is in development, not a licensed bank. Crypto can lose value, including stablecoins, and transfers may be irreversible.','تزدان قيد التطوير وليست مصرفاً مرخّصاً. الكريبتو قد يفقد قيمته، بما فيه العملات المستقرة، والتحويلات قد تكون غير قابلة للاسترجاع.'),
 'footer_disclaimer_protection':('Local payments, crypto services and remittances each depend on applicable approvals, eligible users and contracted providers. No service or deposit protection is implied by the preview.','الدفع المحلي وخدمات الكريبتو والتحويلات تعتمد كل منها على الموافقات والأهلية ومقدمي الخدمة المتعاقدين. العرض لا يعني توفر الخدمة أو ضمان الودائع.'),
 'waitlist_sub':('Be first to hear about our Libyan wallet, crypto and remittance plans. No deposit or commitment.','كون أول من يعرف خطط محفظتنا الليبية والكريبتو والتحويلات. بدون إيداع أو التزام.'),
 'page_fees_row5_s':('LYD funding and crypto conversion','تمويل بالدينار وتحويل كريبتو'),'page_fees_row5_n':('Partner, asset, spread and network fees will be quoted before confirmation.','رسوم الشريك والأصل وفارق السعر والشبكة توضح قبل التأكيد.'),
 'page_fees_row7_s':('International remittances','تحويلات دولية'),'page_fees_row7_n':('Approved corridors only. FX, partner and network costs disclosed in the quote.','مسارات معتمدة فقط. تكاليف الصرف والشريك والشبكة واضحة في العرض.'),
}
for idx,lang in enumerate(['en','ar']):
 p=Path(f'client/src/i18n/{lang}.json');d=json.loads(p.read_text());d.update({k:v[idx] for k,v in copy.items()});p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
p=Path('client/src/app/layout.tsx');s=p.read_text().replace('Your dinar. More possibilities.','Libya. Crypto. Connected.').replace('Payments built around Libya','Crypto and remittances for Libya').replace('a Libyan payments app in the making. Everyday payments in LYD, clearer spending and an international outlook.','a Libyan wallet, crypto and international remittance app in the making. Clear costs in LYD.').replace('Proposed Libyan dinar wallet and local payment service. International features depend on partners and regulatory approval.','Proposed Libyan dinar wallet, supported crypto services and international remittances. Availability depends on providers and regulatory approval.');p.write_text(s)
p=Path('client/src/components/PageTitle.tsx');s=p.read_text().replace('Your dinar. More possibilities.','Libya. Crypto. Connected.').replace('تزدان — دينارك، وإمكانيات أكثر','تزدان — ليبيا، كريبتو وتحويلات دولية');p.write_text(s)
p=Path('client/src/app/page.tsx');s=p.read_text().replace('Proposed payments app for Libya. Everyday payments in LYD, with international services on the roadmap.','Proposed LYD wallet, supported crypto services and international remittances for Libya.').replace("['Planned local payments', 'Planned money transfers']","['Planned LYD wallet', 'Planned crypto services', 'Planned international remittances']");p.write_text(s)
